docker:
  generator: github-1
  packages:
    - docker:
        github:
          user: moby
          repo: moby
          query: releases
        version: 27.3.1
    - docker-cli:
        github:
          user: docker
          repo: cli
          query: tags
        version: 27.3.1
    - docker-compose:
        extensions:
          - golang
        github:
          user: docker
          repo: compose
          query: releases
        version: 2.30.3
    - docker-buildx:
        extensions:
          - golang
        github:
          user: docker
          repo: buildx
          query: releases
        version: 0.18.0
