docker:
  generator: github-1
  packages:
    - docker:
        github:
          user: moby
          repo: moby
          query: releases
        version: 25.0.5
    - docker-cli:
        github:
          user: docker
          repo: cli
          query: tags
        version: 25.0.5
    - docker-compose:
        extensions:
          - golang
        github:
          user: docker
          repo: compose
          query: releases
        version: 2.27.0
    - docker-buildx:
        extensions:
          - golang
        github:
          user: docker
          repo: buildx
          query: releases
        version: 0.14.0
