docker :
  generator: github-1
  packages:
    - docker:
        github:
          user: moby
          repo: moby
          query: releases
        version: 24.0.8
    - docker-cli:
        github:
          user: docker
          repo: cli
          query: tags
        version: 24.0.8
    - docker-compose:
        extensions:
          - golang
        github:
          user: docker
          repo: compose
          query: releases
        version: 2.24.3
    - docker-buildx:
        extensions:
          - golang
        github:
          user: docker
          repo: buildx
          query: releases
        version: 0.12.1
