ansible_pypi_rule:
  generator: pypi-compat-1
  defaults:
    cat: app-admin
    python_compat: pypy3 python3+
    du_pep517: generator
  packages:
    - ansible-core:
        version: latest
        desc: Model-driven deployment, config management, and command execution framework
        homepage: https://ansible.com/
        license: GPL-3
        pydeps:
          - paramiko
          - jinja
          - pyyaml
          - cryptography
          - httplib2
          - six
          - netaddr
          - pexpect
        rdepend: |
          net-misc/sshpass
          virtual/ssh
        bdepend: |
          dev-python/packaging
    - ansible:
        license: GPL-3+
        pydeps:
          - paramiko
          - jinja
          - pyyaml
          - cryptography
          - httplib2
          - six
          - netaddr
          - pexpect
        rdepend: |
          net-misc/sshpass
          virtual/ssh
        bdepend: |
          dev-python/packaging
